### ISSUE TITLE
version 4.2.6 自定义框架提示

### ISSUE THREAD

**Issue by QinHaifeiCN** [jiaolong1021/vue-helper#100]
已经是年度pro,但是无法点击下载。无任何反应，点击文档也是。真的流脓了这东西，付费了就应该开箱即用，纯纯恶心人的东西。 这不浪费别人时间吗。
![00](https://github.com/user-attachments/assets/3188c3c5-3e11-419a-9849-a46abc98c1e5)
![01](https://github.com/user-attachments/assets/5ce8f8b2-99e1-4884-ba23-4d81e3058df0)

**Comment by jiaolong1021** [comment]
兄弟，任何问题都可以直接进群反馈。或者反馈，我们都会处理。

**Comment by QinHaifeiCN** [comment]
> 兄弟，任何问题都可以直接进群反馈。或者反馈，我们都会处理。

直接卸掉了。  还不如别人免费的好用，  我要的是开箱即用的element plus智能提示。按你的文档连最基本的功能都没整出来。 做收费的产品就这样糊弄？ 就这还到处发帖子推销自己的插件，吐了。、
