### ISSUE TITLE
关于删除输入法候选字母后会触发自动补全的bug

### ISSUE THREAD

**Issue by 630865159** [jiaolong1021/vue-helper#101]
![image](https://github.com/user-attachments/assets/e32b4238-f89d-4d8d-b978-02fa35a639a6)
![image](https://github.com/user-attachments/assets/2f8f7702-4fa1-428d-8b05-3ce7498fd668)

**Comment by jiaolong1021** [comment]
收到，测试后会进行相应修复

**Comment by jiaolong1021** [comment]
4.2.7版本已解决
