### ISSUE TITLE
使用该插件后在ts中使用泛型会被当做Html标签自动闭合

### ISSUE THREAD

**Issue by renyancheng** [jiaolong1021/vue-helper#102]
我已经对auto-close-tag插件进行了排除ts操作，安装vue-helper后仍然会对ts文件内的泛型进行自动闭合，非常影响编写代码
![image](https://github.com/user-attachments/assets/5c8a07fd-6504-4703-92b4-f94e3681f7d1)

**Comment by jiaolong1021** [comment]
下个版本优化
