### ISSUE TITLE
Allow for CamelCase

### ISSUE THREAD

**Issue by soniktrooth** [jiaolong1021/vue-helper#11]
This extension seems to dictate kebab case for component names in the HTML section. Is it possible to allow an option for camel case?

**Comment by jiaolong1021** [comment]
it's support import name as camelCase now in version 2.4.3

**Comment by jiaolong1021** [comment]
![image](https://user-images.githubusercontent.com/13686859/81174691-dce42780-8fd4-11ea-8765-87074c528a3d.png)
you can set the way in vscode settings.
