### ISSUE TITLE
can't jump to definition when '.vue' is omitted like belowup

### ISSUE THREAD

**Issue by ZhongJinMing** [jiaolong1021/vue-helper#26]
hi, Thank you for providing this great tool. But when I want to jump to definition like below, it can't work.
![image](https://user-images.githubusercontent.com/24693491/103336826-5248bf00-4ab4-11eb-95e0-e30dd1a26dc2.png)
when I add .vue to those component it can work well
help me, thank you!

**Comment by sharkrice** [comment]
+1

**Comment by jiaolong1021** [comment]
already support
