### ISSUE TITLE
How to disable the code completion or only completion with prefix

### ISSUE THREAD

**Issue by chenjiangui** [jiaolong1021/vue-helper#27]
now when doesn't use element, the code competion will show.  And it's will show after i input some words, can only completion with prefix

**Comment by jiaolong1021** [comment]
you can remove the snippet in plugin
![image](https://user-images.githubusercontent.com/13686859/104454281-970a4500-55e0-11eb-99b5-fb04a43c43f0.png)

**Comment by jiaolong1021** [comment]
![image](https://user-images.githubusercontent.com/13686859/104454331-a8ebe800-55e0-11eb-983f-19493cc21905.png)

**Comment by jiaolong1021** [comment]
<img width="725" alt="Snipaste_2021-01-13_20-49-31" src="https://user-images.githubusercontent.com/13686859/104454475-ddf83a80-55e0-11eb-8375-ec8fe9b0192b.png">

**Comment by chenjiangui** [comment]
thanks
