### ISSUE TITLE
请问snippets是怎么生成的 https://github.com/jiaolong1021/vue-helper/blob/master/snippets/element-html.json

### ISSUE THREAD

**Issue by hytStart** [jiaolong1021/vue-helper#32]
大佬请问snippets是怎么生成的 https://github.com/jiaolong1021/vue-helper/blob/master/snippets/element-html.json

**Comment by jiaolong1021** [comment]
这个是自己对着element官网整理的，也可以通过脚本去爬下来。

**Comment by hytStart** [comment]
> 这个是自己对着element官网整理的，也可以通过脚本去爬下来。

昂昂，感觉纯整理，还是有点费事的。

**Comment by cooper1x** [comment]
@jiaolong1021 这个element ui的snippets可以自行修改自定义吗？

**Comment by jiaolong1021** [comment]
这个无法修改，不过可以自己在snippets里面重新自定义一个
