### ISSUE TITLE
alias 是否可以设置多个?

### ISSUE THREAD

**Issue by Arech-github** [jiaolong1021/vue-helper#36]
"vue-helper.alias": {
        "@": "./src",
        // "@drComponents": "./src/platform/doctor/components",
    },

单独配置 @  在 template里  是可以跳转的 

但是使用@drComponents  无法跳转   

是我使用的问题吗

**Comment by jiaolong1021** [comment]
可以设置多个，别名@drComponents中的@需要换成其他的

**Comment by Arech-github** [comment]
可以设置成不换的吗        我还有许多其他的别名
