### ISSUE TITLE
is:issue state:open "Extension causes high cpu load" 

### ISSUE THREAD

**Issue by AbdulRafaySalsoftNew** [jiaolong1021/vue-helper#37]
is:issue state:open "Extension causes high cpu load"

**Comment by AbdulRafaySalsoftNew** [comment]
[shenjiaolong.vue-helper-unresponsive.cpuprofile.txt](https://github.com/jiaolong1021/vue-helper/files/6684986/shenjiaolong.vue-helper-unresponsive.cpuprofile.txt)

**Comment by YangZhaocool** [comment]
win10 
vscode 1.58.2
same problem
