### ISSUE TITLE
作者是不是不维护了

### ISSUE THREAD

**Issue by YangZhaocool** [jiaolong1021/vue-helper#38]
这个插件用的太顺手了
现在用着用着就开始加载时间格外的长
看了控制台 插件的状态基本都是unresponsive

**Comment by jiaolong1021** [comment]
维护

**Comment by YangZhaocool** [comment]
那就抽时间帮忙搞搞优化吧大佬
这个插件真的是用的太顺手了 就是现在总会莫名的卡死
