### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LeeDashan** [jiaolong1021/vue-helper#4]
- Issue Type: `Performance`
- Extension Name: `vue-helper`
- Extension Version: `2.1.8`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/limaoqun/shenjiaolong.vue-helper-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by AbdulRafaySalsoftNew** [comment]
[shenjiaolong.vue-helper-unresponsive.cpuprofile.txt](https://github.com/jiaolong1021/vue-helper/files/6725282/shenjiaolong.vue-helper-unresponsive.cpuprofile.txt)
