### ISSUE TITLE
definition jump feature can't jump to async function

### ISSUE THREAD

**Issue by tjx666** [jiaolong1021/vue-helper#5]
<img width="624" alt="Snipaste_2019-09-24_11-11-49" src="https://user-images.githubusercontent.com/41773861/65478381-25265d80-debc-11e9-8e19-b557508b9081.png">

Using `CMD + mouse click` to jump to clicked variable's definition is very useful. When I use `CMD + mouse click `to jump to an async function, It seems the extension can't find the definition.

**Comment by jiaolong1021** [comment]
already finished in version 2.1.15
