### ISSUE TITLE
element ui doc 域名地址更改了，希望更新一下

### ISSUE THREAD

**Issue by yinluobing** [jiaolong1021/vue-helper#57]
element ui doc 域名地址更改了，希望更新一下

**Comment by yinluobing** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/5945624/183624257-e4901f2e-8ed8-4180-b70a-4a4ffd535b16.png">

http://element-cn.eleme.io/ 改为 http://element.eleme.io/

**Comment by jiaolong1021** [comment]
thank you for your advice， will changed in version 2.5.0
