### ISSUE TITLE
I can't enter the Enter key every time I restart.

### ISSUE THREAD

**Issue by tjx666** [jiaolong1021/vue-helper#6]
每次重启敲回车，然后右下角报图中的那个错误。
<img width="1439" alt="Snipaste_2019-09-28_17-48-42" src="https://user-images.githubusercontent.com/41773861/65814750-6c904f00-e218-11e9-87ee-149c456999d4.png">

**Comment by jiaolong1021** [comment]
this question has no best solution way now,
i am trying to resolve as soon as possible.

**Comment by jiaolong1021** [comment]
this question resolved.
