### ISSUE TITLE
BUG: auto-complete tag has not stop

### ISSUE THREAD

**Issue by IOLOII** [jiaolong1021/vue-helper#64]
while type tag with "<" ,">" or "/" in *.vue file <template></template> area ,
there has one error : couldn't stop insert input value

here is error video only for change vue-helper Enable or Disable:

https://user-images.githubusercontent.com/34856171/227500895-2b4e9c78-cdc6-44d7-a9a4-1e58555ca7f0.mp4

**Comment by jiaolong1021** [comment]
will resolve in version 2.5.0
