### ISSUE TITLE
莫名补齐标签或符号 

### ISSUE THREAD

**Issue by XiaSean** [jiaolong1021/vue-helper#71]
写{{}} 双大括号时,这个插件会莫名多补出右边一个大括号, 也就是左边两个大括号,右边三个大括号, 把这个插件卸载了就没有这个问题.
这个问题不仅出现在大括号上, 键盘打快了 右边莫名会给你多补出一个元素,希望作者赶紧修复

**Comment by jiaolong1021** [comment]
正在准备重构中...
