### ISSUE TITLE
2.5.0 BUG 无法使用退格键

### ISSUE THREAD

**Issue by DarkGhast** [jiaolong1021/vue-helper#72]
在.js、.vue文件中使用退格无法删除任何字符，关闭vue-helper后恢复正常
![image](https://github.com/jiaolong1021/vue-helper/assets/44697474/8e3de2c1-ad30-434b-a9ff-5684f11eb407)

**Comment by Darkingtail** [comment]
+1

**Comment by hao-xh** [comment]
+1

**Comment by jiaolong1021** [comment]
![image](https://github.com/jiaolong1021/vue-helper/assets/13686859/71d6a0c6-fb2c-46f2-a26a-88460b15d2aa)
可以在快捷键中先关掉该功能，或者重新安装试下。这种情况极有可能是插件没有触发。我优化一下。

**Comment by ADDGM** [comment]
同样的问题，但我的可以使用Shift+Backspace

**Comment by MAY-ZHONGYE** [comment]
貌似鼠标悬停在标签上也没有文档提示了。。。
![image](https://github.com/jiaolong1021/vue-helper/assets/93515822/189cff71-fd1d-4cdc-8d94-67e331a9bce3)

**Comment by jiaolong1021** [comment]
package.json中引入了element了吗？

**Comment by jiaolong1021** [comment]
有问题可以加群反馈

**Comment by jiaolong1021** [comment]
该问题已在2.5.1解决
