### ISSUE TITLE
更新完之后, 方法跳转无法使用

### ISSUE THREAD

**Issue by xiaojia21190** [jiaolong1021/vue-helper#74]
请问一下, 怎么更新老版本

**Comment by jiaolong1021** [comment]
更新的最新版吗？

**Comment by xiaojia21190** [comment]
更新的最新版, 但是我用过的是vim , 应该跟这个没关系, 更新到老版本没问题

**Comment by xiaojia21190** [comment]
![image](https://github.com/jiaolong1021/vue-helper/assets/16084693/3d35aca5-3cdd-44b5-ba3b-ab77125f68bc)

**Comment by jiaolong1021** [comment]
2.4的版本吗？

**Comment by jiaolong1021** [comment]
https://marketplace.visualstudio.com/items?itemName=shenjiaolong.vue-helper

**Comment by jiaolong1021** [comment]
这里可以下载安装

**Comment by jiaolong1021** [comment]
能截图看下跳转具体哪里不能用不？

**Comment by xiaojia21190** [comment]
> 能截图看下跳转具体哪里不能用不？

![image](https://github.com/jiaolong1021/vue-helper/assets/16084693/9369adfc-274c-4358-b0e0-395acbd55e30)

**Comment by jiaolong1021** [comment]
![jump](https://github.com/jiaolong1021/vue-helper/assets/13686859/b0cf688f-2f60-4fdd-b77a-0dd4b08e406d)

**Comment by jiaolong1021** [comment]
不知你是组合式还是选项式
