### ISSUE TITLE
新版本无代码提示和函数跳转

### ISSUE THREAD

**Issue by MAY-ZHONGYE** [jiaolong1021/vue-helper#75]
框架使用的是vue2
2.4.7版本是没问题的，是不兼容的吗？
这是2.4.7：
![image](https://github.com/jiaolong1021/vue-helper/assets/93515822/d18ba090-126a-4f5c-9bed-b63f84b17703)
这是新版本：
![image](https://github.com/jiaolong1021/vue-helper/assets/93515822/4f4ca7a1-364c-4bb8-8bf6-6ed4aa931866)
packagejson也引入ElementUI了
![image](https://github.com/jiaolong1021/vue-helper/assets/93515822/0bf802ad-e782-4794-bd1d-179dbcd400e4)

**Comment by jiaolong1021** [comment]
vscode版本是多少

**Comment by MAY-ZHONGYE** [comment]
VS版本是1.89.1

**Comment by poison998** [comment]
相同问题

**Comment by xuxygo** [comment]
相同问题

**Comment by jiaolong1021** [comment]
能加群反馈不？

**Comment by jiaolong1021** [comment]
目前用两台测试没有发现这个问题，需要帮忙重现才知道问题在哪？🤝

**Comment by jiaolong1021** [comment]
https://www.80fight.cn/helper/wxq.png

**Comment by jiaolong1021** [comment]
2.6.0版本解决
