### ISSUE TITLE
能否将相关组件文档地址做成可配置式

### ISSUE THREAD

**Issue by sweetwisdom** [jiaolong1021/vue-helper#79]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/5945624/183624257-e4901f2e-8ed8-4180-b70a-4a4ffd535b16.png">

http://element-cn.eleme.io/ 改为 http://element.eleme.io/

_Originally posted by @yinluobing in https://github.com/jiaolong1021/vue-helper/issues/57#issuecomment-1209188805_
            大佬你好，
国内用户打开element-ui会自动跳转到cn，如果支持自定义前缀，插件支持私有文档，扩展性更强

**Comment by jiaolong1021** [comment]
这个提议很好，可以考虑

**Comment by jiaolong1021** [comment]
已支持自定义配置
