### ISSUE TITLE
和Vetur插件同时启用会导致退格键失效

### ISSUE THREAD

**Issue by kang558** [jiaolong1021/vue-helper#8]
Vscode版本：
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

window10下 和Vetur插件同时启用会导致退格键失效
具体复现：
 在vue文件 import xxx from '../xxx' 的时候就会出现，其他情况也偶尔不明原因出现

**Comment by jiaolong1021** [comment]
thank you feedback the question. this question already resolved in 2.3.3

**Comment by jiaolong1021** [comment]
if you want use the backspace to delete multi line empty. you can set the short cut by yourself.
![image](https://user-images.githubusercontent.com/13686859/77931325-9cf79980-72de-11ea-97d5-72df08c3a1fb.png)
