### ISSUE TITLE
新加的功能，貌似影响了启动速度， 之前200ms现在得2000ms

### ISSUE THREAD

**Issue by xiaojia21190** [jiaolong1021/vue-helper#84]
是否可以做功能的加载优化

**Comment by jiaolong1021** [comment]
好的，我关注下。

**Comment by lws123321** [comment]
影响太多了。。我的直接变成20多秒

**Comment by lws123321** [comment]
![image](https://github.com/jiaolong1021/vue-helper/assets/71438345/8106a165-4da4-4744-84ab-5b02b3f432a5)
我发现从2.5版本开始就是

**Comment by jiaolong1021** [comment]
4.0.0版本开始已经进行了优化
