### ISSUE TITLE
ElementPlus无代码提示

### ISSUE THREAD

**Issue by Arvinsyt** [jiaolong1021/vue-helper#85]
VSCode版本: 1.90.0
Vue-helper版本: 3.4.0
Vue版本: Vue3
我测试了2.6.2和3.0.0版本是能正常提示的
<img width="451" alt="Code_EVlDE7IJ7K" src="https://github.com/jiaolong1021/vue-helper/assets/133661228/1f926e0d-2505-4b78-a415-f4bcd874153f">
但是3.1.0和3.4.0都没有任何提示
<img width="454" alt="Code_914FiKs11g" src="https://github.com/jiaolong1021/vue-helper/assets/133661228/6abfaf08-a150-4904-9e13-cb2f4eaaccd6">

**Comment by jiaolong1021** [comment]
这个属于pro功能，需要试用才能提示了
