### ISSUE TITLE
不提示

### ISSUE THREAD

**Issue by gyjx** [jiaolong1021/vue-helper#88]
vscode：1.90.0
vue-helper：v3.5.2
element-plus：2.7.5
vue：3.4.21

![image](https://github.com/jiaolong1021/vue-helper/assets/20329819/aca5324a-44ba-4fa8-89dc-8b5113e1a514)

![image](https://github.com/jiaolong1021/vue-helper/assets/20329819/cb0af8d2-e697-423d-b6ea-6d014d98ede4)

![image](https://github.com/jiaolong1021/vue-helper/assets/20329819/ea8a4d55-10c9-4dff-9043-332f0a079df7)

已经申请试用了。

**Comment by jiaolong1021** [comment]
mac版本吗？

**Comment by gyjx** [comment]
windows10



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月18日(周二) 晚上9:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jiaolong1021/vue-helper] 不提示 (Issue #88)




 
mac版本吗？

**Comment by gyjx** [comment]
![image](https://github.com/jiaolong1021/vue-helper/assets/20329819/2fc15dd5-521b-4af2-9ea3-875e1a9bdbc1)
这是我的vscode安装的所有插件，供你们参考！

**Comment by lws123321** [comment]
4.0版本不提示了
![image](https://github.com/jiaolong1021/vue-helper/assets/71438345/566e268e-3a67-479d-a319-7cf8e388239f)

![image](https://github.com/jiaolong1021/vue-helper/assets/71438345/22ea14a0-4c54-45f3-837b-df024ec9fde5)

**Comment by jiaolong1021** [comment]
![image](https://github.com/jiaolong1021/vue-helper/assets/13686859/b8e31be3-af14-4204-b29a-6a3811280557)

**Comment by lws123321** [comment]
![1720164337018_d](https://github.com/jiaolong1021/vue-helper/assets/71438345/19cd8bc8-25c9-4a34-8167-f685ef2a26fc)
没找到这个配置项哦

**Comment by lws123321** [comment]
![ae20a21a602b7ab2cd4a7968e877bb0](https://github.com/jiaolong1021/vue-helper/assets/71438345/a4b0083a-5ada-413e-ab1a-f9bb891cccdb)
没有找到这个配置哦
