### ISSUE TITLE
[auto import file] 路徑問題

### ISSUE THREAD

**Issue by liubusian** [jiaolong1021/vue-helper#9]
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

vue-helper: 2.3.1

當使用auto import file
得到
import myHeader from '@\components\myHeader'  => 會導致錯誤

我查看源碼，是由於使用path.sep，在windows會使用反斜線導致，是否加入判斷，當path.sep為反斜線的時候，使用正斜線(/)呢?

**Comment by jiaolong1021** [comment]
this question already resolve in version 2.3.3
