### ISSUE TITLE
插件未生效

### ISSUE THREAD

**Issue by L51xyz12138** [jiaolong1021/vue-helper#92]
作者您好，插件非常好用，但是我最近自从版本更新后插件就不生效了。请问能修复一下吗？电脑系统为Windows11

**Comment by jiaolong1021** [comment]
可以具体描述下是某个功能不生效，还是不能用了呢？

**Comment by L51xyz12138** [comment]
您好，是1.1组件代码块生成、1.2属性提示、1.3文档查看，官网跳转这些功能不能生效。其他的我看还是可以的
![2](https://github.com/jiaolong1021/vue-helper/assets/66251145/985f10e3-d54d-4991-b61b-2ae4141c271b)
![3](https://github.com/jiaolong1021/vue-helper/assets/66251145/42fdf42f-6e90-4d43-b94c-161e6423624a)
![1](https://github.com/jiaolong1021/vue-helper/assets/66251145/3806b318-a2bc-412f-9fc3-36fe1701a7db)

**Comment by jiaolong1021** [comment]
element-plus的话，需要申请试用才会有。🤝
![image](https://github.com/jiaolong1021/vue-helper/assets/13686859/c10ffe95-c49c-461a-9bdd-e5d722f1e678)
