### ISSUE TITLE
将Typescript中的类型标识当作Html标签自动补全

### ISSUE THREAD

**Issue by zhiyangjing** [jiaolong1021/vue-helper#93]
具体情况如下：

使用的插件版本是 v4.0.0。 在vue文件下的 `<script lang="ts">` 标签中稳定出现该问题。关闭该插件之后改问题消失。

![动画](https://github.com/jiaolong1021/vue-helper/assets/108873506/c84f0a61-7d0b-4024-986f-ab80061596d9)

**Comment by jiaolong1021** [comment]
已收到反馈，该问题将在下个版本解决
