### ISSUE TITLE
有的文件跳转时会提示未找到“queryParams”的任何定义,无法跳转

### ISSUE THREAD

**Issue by kl79613** [jiaolong1021/vue-helper#94]
<img width="726" alt="image" src="https://github.com/user-attachments/assets/92649dd7-dbd4-4620-bfc8-89a03ec2358f">
<img width="451" alt="image" src="https://github.com/user-attachments/assets/bbc110f0-53df-4a6b-8791-c358a892b649">

vue-helper v4.1.0
Visual Studio Code 版本: 1.90.2 (Universal)

**Comment by jiaolong1021** [comment]
已解决
